version: 2.1

orbs:
  chatwork: decoch/chatwork@0.0.1

jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - chatwork/notify:
        message: "Notification test for the chatwork-orb"
        room-id: "14630985"

workflows:
   main:
     jobs:
     - build

